# Generated by Django 4.1.6 on 2023-02-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('submission_id', models.CharField(max_length=50)),
                ('option_choice', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
