# Generated by Django 4.1.6 on 2023-02-17 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_answer_alter_user_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Attempt_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
