# Generated by Django 4.1.6 on 2023-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_answer_attempt_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submission_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
